### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by SimonStochholm** [a11to1n3/tsem#1]
UWaveGestureLibrary dataset works out of the box with TSEM, but AbnormalHeartbeat dataset (from same location) does not. How should the dataset be formattet in order to work with TSEM?

**Comment by a11to1n3** [comment]
Hi, could you show me your data shape?

**Comment by SimonStochholm** [comment]
Hi Anh-Duy Pham
The description of the dataset I am trying to use can be found here:
https://www.timeseriesclassification.com/description.php?Dataset=AbnormalHeartbeat

Best, Simon Stochholm

From: Anh-Duy Pham ***@***.***>
Reply to: a11to1n3/tsem ***@***.***>
Date: Monday, 12 August 2024 at 11.02
To: a11to1n3/tsem ***@***.***>
Cc: Simon Stochholm ***@***.***>, Author ***@***.***>
Subject: Re: [a11to1n3/tsem] Dataset format (Issue #1)


Hi, could you show me your data shape?

**Comment by a11to1n3** [comment]
Hello Simon, 

thank you for reaching out. Apparently, the dataset is a set of univariate time series and TSEM cannot work on univariate time series. If you still want to use TSEM, please consider do some feature engineering methods and stack more feature along with the original time series and then it will work.

Best,
Duy

**Comment by SimonStochholm** [comment]
Okay, thank you.
________________________________
Fra: Anh-Duy Pham ***@***.***>
Sendt: Monday, August 12, 2024 11:15:42 AM
Til: a11to1n3/tsem ***@***.***>
Cc: Kampmarsvin ***@***.***>; Author ***@***.***>
Emne: Re: [a11to1n3/tsem] Dataset format (Issue #1)


Hello Simon,

thank you for reaching out. Apparently, the dataset is a set of univariate time series and TSEM cannot work on univariate time series. If you still want to use TSEM, please consider do some feature engineering methods and stack more feature along with the original time series and then it will work.

Best,
Duy

**Comment by a11to1n3** [comment]
You're welcome! If you would have more features and would like to try TSEM again, I am happy to assist.
